### ISSUE TITLE
(README) Assistance Needed

### ISSUE THREAD

**Issue by GracioussBoww** [ImaginaryGate/imaginarygate.github.io#1]
Hey so im Graciouss, im looking to build a discord bot and I've got as far as getting it online but I'm struggling a little.

Im needing help with adding a prefix to it. The nature of the bot is for an RP server and I need it to have a high number of custom commands as a feature. Please note I'm on a Chromebook so any help with all of this is appreciated a lot.

Contact me @GracioussBoww#9958 on discord

**Comment by ImaginaryGate** [comment]
Hey Graciouss, with a quick google search you can find tons and tons of solutions to issues like this. You didn't specify the framework you're working with but assuming you're using Discord.js, I'd recommend this websites tutorials: [discordjs.guide](https://discordjs.guide/).

**Comment by GracioussBoww** [comment]
> Hey Graciouss, with a quick google search you can find tons and tons of solutions to issues like this. You didn't specify the framework you're working with but assuming you're using Discord.js, I'd recommend this website's tutorials: [discordjs.guide](https://discordjs.guide/).

Thanks, I'm working with node.js, been looking all over and just keeps returning dead ends. I Will update here if I get nowhere.
